export const CREATE_ACTION_HERE = 'CREATE_ACTION_HERE'

//DOMAIN
export const DOMAIN = 'http://localhost:3010'

//HEADER
export const HEADER = { 'Content-Type': 'application/json' }

//Limit
export const LIMIT = 5
export const LIMITFIME = 5
//Method
export const GET = 'GET'
export const POST = 'POST'
export const PUT = 'PUT'
export const DELETE = 'DELETE'

export const GET_NEW_FILM_REQUEST = 'GET_NEW_FILM_REQUEST'
export const GET_NEW_FILM_SUCCESS = 'GET_NEW_FILM_SUCCESS'
export const GET_NEW_FILM_FAILURE = 'GET_NEW_FILM_FAILURE'

export const GET_NOT_NEW_FILM_REQUEST = 'GET_NOT_NEW_FILM_REQUEST'
export const GET_NOT_NEW_FILM_SUCCESS = 'GET_NOT_NEW_FILM_SUCCESS'
export const GET_NOT_NEW_FILM_FAILURE = 'GET_NOT_NEW_FILM_FAILURE'

export const GET_NOT_HOT_FILM_REQUEST = 'GET_NOT_HOT_FILM_REQUEST'
export const GET_NOT_HOT_FILM_SUCCESS = 'GET_NOT_HOT_FILM_SUCCESS'
export const GET_NOT_HOT_FILM_FAILURE = 'GET_NOT_HOT_FILM_FAILURE'

export const GET_COMING_SOON_FILM_REQUEST = 'GET_COMING_SOON_FILM_REQUEST'
export const GET_COMING_SOON_FILM_SUCCESS = 'GET_COMING_SOON_FILM_SUCCESS'
export const GET_COMING_SOON_FILM_FAILURE = 'GET_COMING_SOON_FILM_FAILURE'

export const GET_IN_THEATER_FILM_REQUEST = 'GET_IN_THEATER_FILM_REQUEST'
export const GET_IN_THEATER_FILM_SUCCESS = 'GET_IN_THEATER_FILM_SUCCESS'
export const GET_IN_THEATER_FILM_FAILURE = 'GET_IN_THEATER_FILM_FAILURE'

export const GET_GENRE_FILM_REQUEST = 'GET_GENRE_FILM_REQUEST'
export const GET_GENRE_FILM_SUCCESS = 'GET_GENRE_FILM_SUCCESS'
export const GET_GENRE_FILM_FAILURE = 'GET_GENRE_FILM_REQUEST'

export const GET_HOT_FILM_REQUEST = 'GET_HOT_FILM_REQUEST'
export const GET_HOT_FILM_SUCCESS = 'GET_HOT_FILM_SUCCESS'
export const GET_HOT_FILM_FAILURE = 'GET_HOT_FILM_FAILURE'

export const GET_FILM_DETAIL_REQUEST = 'GET_FILM_DETAIL_REQUEST'
export const GET_FILM_DETAIL_SUCCESS = 'GET_FILM_DETAIL_SUCCESS'
export const GET_FILM_DETAIL_FAILURE = 'GET_FILM_DETAIL_FAILURE'

export const GET_CINEMA_DETAIL_REQUEST = 'GET_CINEMA_DETAIL_REQUEST'
export const GET_CINEMA_DETAIL_SUCCESS = 'GET_CINEMA_DETAIL_SUCCESS'
export const GET_CINEMA_DETAIL_FAILURE = 'GET_CINEMA_DETAIL_FAILURE'
export const GET_CINEMAS_CLUSTER_REQUEST = 'GET_CINEMAS_CLUSTER_REQUEST'
export const GET_CINEMAS_CLUSTER_SUCCESS = 'GET_CINEMAS_CLUSTER_SUCCESS'
export const GET_CINEMAS_CLUSTER_FAILURE = 'GET_CINEMAS_CLUSTER_FAILURE'

export const GET_DETAIL_CINEMA_CLUSTER_REQUEST =
  'GET_DETAIL_CINEMA_CLUSTER_REQUEST'
export const GET_DETAIL_CINEMA_CLUSTER_SUCCESS =
  'GET_DETAIL_CINEMA_CLUSTER_SUCCESS'
export const GET_DETAIL_CINEMA_CLUSTER_FAILURE =
  'GET_DETAIL_CINEMA_CLUSTER_FAILURE'

export const GET_SEARCH_FILM_REQUEST = 'GET_SEARCH_FILM_REQUEST'
export const GET_SEARCH_FILM_SUCCESS = 'GET_SEARCH_FILM_SUCCESS'
export const GET_SEARCH_FILM_FAILURE = 'GET_SEARCH_FILM_FAILURE'

// ...............Nav..................

export const GET_ALL_FILM_ADMIN_REQUEST = 'GET_ALL_FILM_ADMIN_REQUEST'
export const GET_ALL_FILM_ADMIN_SUCCESS = 'GET_ALL_FILM_ADMIN_SUCCESS'
export const GET_ALL_FILM_ADMIN_FAILURE = 'GET_ALL_FILM_ADMIN_FAILURE'

export const GET_HOT_FILM_ADMIN_REQUEST = 'GET_HOT_FILM_ADMIN_REQUEST'
export const GET_HOT_FILM_ADMIN_SUCCESS = 'GET_HOT_FILM_ADMIN_SUCCESS'
export const GET_HOT_FILM_ADMIN_FAILURE = 'GET_HOT_FILM_ADMIN_FAILURE'

export const GET_FILM_PAGINATION_REQUEST = 'GET_FILM_PAGINATION_REQUEST'
export const GET_FILM_PAGINATION_SUCCESS = 'GET_FILM_PAGINATION_SUCCESS'
export const GET_FILM_PAGINATION_FAILURE = 'GET_FILM_PAGINATION_FAILURE'

export const SEARCH_FILM_ADMIN_REQUEST = 'SEARCH_FILM_ADMIN_REQUEST'
export const SEARCH_FILM_ADMIN_SUCCESS = 'SEARCH_FILM_ADMIN_SUCCESS'
export const SEARCH_FILM_ADMIN_FAILURE = 'SEARCH_FILM_ADMIN_FAILURE'

export const SEARCH_ALL_FILM_ADMIN_REQUEST = 'SEARCH_ALL_FILM_ADMIN_REQUEST'
export const SEARCH_ALL_FILM_ADMIN_SUCCESS = 'SEARCH_ALL_FILM_ADMIN_SUCCESS'
export const SEARCH_ALL_FILM_ADMIN_FAILURE = 'SEARCH_ALL_FILM_ADMIN_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const ADD_FILM_REQUEST = 'ADD_FILM_REQUEST'
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS'
export const ADD_FILM_FAILURE = 'ADD_FILM_FAILURE'

export const ADD_ACTOR_REQUEST = 'ADD_ACTOR_REQUEST'
export const ADD_ACTOR_SUCCESS = 'ADD_ACTOR_SUCCESS'
export const ADD_ACTOR_FAILURE = 'ADD_ACTOR_FAILURE'

export const ADD_CINEMA_CLUSTER_REQUEST = 'ADD_CINEMA_CLUSTER_REQUEST'
export const ADD_CINEMA_CLUSTER_SUCCESS = 'ADD_CINEMA_CLUSTER_SUCCESS'
export const ADD_CINEMA_CLUSTER_FAILURE = 'ADD_CINEMA_CLUSTER_FAILURE'

export const ADD_CINEMA_REQUEST = 'ADD_CINEMA_REQUEST'
export const ADD_CINEMA_SUCCESS = 'ADD_CINEMA_SUCCESS'
export const ADD_CINEMA_FAILURE = 'ADD_CINEMA_FAILURE'

export const GET_ACTOR_REQUEST = 'GET_ACTOR_REQUEST'
export const GET_ACTOR_SUCCESS = 'GET_ACTOR_SUCCESS'
export const GET_ACTOR_FAILURE = 'GET_ACTOR_FAILURE'

export const GET_CINEMA_ADMIN_REQUEST = 'GET_CINEMA_ADMIN_REQUEST'
export const GET_CINEMA_ADMIN_SUCCESS = 'GET_CINEMA_ADMIN_SUCCESS'
export const GET_CINEMA_ADMIN_FAILURE = 'GET_CINEMA_ADMIN_FAILURE'

export const SEARCH_ACTOR_REQUEST = 'SEARCH_ACTOR_REQUEST'
export const SEARCH_ACTOR_SUCCESS = 'SEARCH_ACTOR_SUCCESS'
export const SEARCH_ACTOR_FAILURE = 'SEARCH_ACTOR_FAILURE'

export const GET_GENRE_FILM_ADMIN_REQUEST = 'GET_GENRE_FILM_ADMIN_REQUEST'
export const GET_GENRE_FILM_ADMIN_SUCCESS = 'GET_GENRE_FILM_ADMIN_SUCCESS'
export const GET_GENRE_FILM_ADMIN_FAILURE = 'GET_GENRE_FILM_ADMIN_FAILURE'

export const UPDATE_FILM_REQUEST = 'UPDATE_FILM_REQUEST'
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS'
export const UPDATE_FILM_FAILURE = 'UPDATE_FILM_FAILURE'

export const UPDATE_HOT_FILM_REQUEST = 'UPDATE_HOT_FILM_REQUEST'
export const UPDATE_HOT_FILM_SUCCESS = 'UPDATE_HOT_FILM_SUCCESS'
export const UPDATE_HOT_FILM_FAILURE = 'UPDATE_HOT_FILM_FAILURE'

export const UPDATE_NEW_FILM_REQUEST = 'UPDATE_NEW_FILM_REQUEST'
export const UPDATE_NEW_FILM_SUCCESS = 'UPDATE_NEW_FILM_SUCCESS'
export const UPDATE_NEW_FILM_FAILURE = 'UPDATE_NEW_FILM_FAILURE'

export const UPDATE_ACTOR_REQUEST = 'UPDATE_ACTOR_REQUEST'
export const UPDATE_ACTOR_SUCCESS = 'UPDATE_ACTOR_SUCCESS'
export const UPDATE_ACTOR_FAILURE = 'UPDATE_ACTOR_FAILURE'

export const DELETE_FILM_ADMIN_REQUEST = 'DELETE_FILM_ADMIN_REQUEST'
export const DELETE_FILM_ADMIN_SUCCESS = 'DELETE_FILM_ADMIN_SUCCESS'
export const DELETE_FILM_ADMIN_FAILURE = 'DELETE_FILM_ADMIN_FAILURE'

export const DELETE_LIVE_FILM_REQUEST = 'DELETE_LIVE_FILM_REQUEST'
export const DELETE_LIVE_FILM_SUCCESS = 'DELETE_LIVE_FILM_SUCCESS'
export const DELETE_LIVE_FILM_FAILURE = 'DELETE_LIVE_FILM_FAILURE'

export const DELETE_HOT_FILM_REQUEST = 'DELETE_HOT_FILM_REQUEST'
export const DELETE_HOT_FILM_SUCCESS = 'DELETE_HOT_FILM_SUCCESS'
export const DELETE_HOT_FILM_FAILURE = 'DELETE_HOT_FILM_FAILURE'

export const DELETE_NEW_FILM_REQUEST = 'DELETE_NEW_FILM_REQUEST'
export const DELETE_NEW_FILM_SUCCESS = 'DELETE_NEW_FILM_SUCCESS'
export const DELETE_NEW_FILM_FAILURE = 'DELETE_NEW_FILM_FAILURE'

export const DELETE_CINEMA_REQUEST = 'DELETE_CINEMA_REQUEST'
export const DELETE_CINEMA_SUCCESS = 'DELETE_CINEMA_SUCCESS'
export const DELETE_CINEMA_FAILURE = 'DELETE_CINEMA_REQUEST'

export const DELETE_ACTOR_REQUEST = 'DELETE_ACTOR_REQUEST'
export const DELETE_ACTOR_SUCCESS = 'DELETE_ACTOR_SUCCESS'
export const DELETE_ACTOR_FAILURE = 'DELETE_ACTOR_FAILURE'

export const UPDATE_CINEMA_CLUSTER_REQUEST = 'UPDATE_CINEMA_CLUSTER_REQUEST'
export const UPDATE_CINEMA_CLUSTER_SUCCESS = 'UPDATE_CINEMA_CLUSTER_SUCCESS'
export const UPDATE_CINEMA_CLUSTER_FAILURE = 'UPDATE_CINEMA_CLUSTER_FAILURE'

export const GET_CINEMA_REQUEST = 'GET_CINEMA_REQUEST'
export const GET_CINEMA_SUCCESS = 'GET_CINEMA_SUCCESS'
export const GET_CINEMA_FAILURE = 'GET_CINEMA_FAILURE'

export const CLEAR_TEMP_CINEMA = 'CLEAR_TEMP_CINEMA'
